apiVersion: v1
kind: Secret
metadata:
  name: store-thing-secret
type: Opaque
data:
  POSTGRES_DB: c3RvcmU=
  POSTGRES_USER: cG9zdGdyZXM=
  POSTGRES_PASSWORD: NzUwOA==
  POSTGRES_URL: amRiYzpwb3N0Z3Jlc3FsOi8vcG9zdGdyZXM6NTQzMi9zdG9yZQ==