apiVersion: apps/v1
kind: Deployment
metadata:
  name: store-rest-deployment
spec:
  selector:
    matchLabels:
      applicationFullName: store-rest
      application: rest
  template:
    metadata:
      labels:
        applicationFullName: store-rest
        application: rest
    spec:
      containers:
        - name: store-rest
          image: kirbel74/rest
          imagePullPolicy: "IfNotPresent"
          ports:
            - containerPort: 8080
          resources:
            limits:
              memory: "100Mi"
              cpu: "500m"
          env:
            - name: POSTGRES_DB
              valueFrom:
                secretKeyRef:
                  name: store-rest-secret
                  key: POSTGRES_DB
            - name: POSTGRES_USER
              valueFrom:
                secretKeyRef:
                  name: store-rest-secret
                  key: POSTGRES_USER
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: store-rest-secret
                  key: POSTGRES_PASSWORD
            - name: POSTGRES_URL
              valueFrom:
                secretKeyRef:
                  name: store-rest-secret
                  key: POSTGRES_URL